version: '3.9'
services:
  backend:
    build: ./backend
    container_name: painel_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: painel_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  db:
    image: postgres:15
    container_name: painel_db
    restart: always
    environment:
      POSTGRES_USER: painel
      POSTGRES_PASSWORD: painel123
      POSTGRES_DB: painel_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: